T3
AnyCase-Company-LTD/NugetAnalyzer pull request #12
Opened 2019-04-23 09:21 UTC by pipalalala

Repository and UnitOfWork were made

2019-04-23 09:27 UTC, AntsiferauGodel requested changes

2019-04-23 09:27 UTC, AntsiferauGodel commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +                .ToList();
Where returns IEnumerable, no need for ToList...)

2019-04-23 09:30 UTC, pipalalala commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +                .ToList();
Done

2019-04-23 09:32 UTC, pryabov commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +            context.Set<T>().Add(item);
Can it be done as a Property?

2019-04-23 11:41 UTC, pipalalala commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +            context.Set<T>().Add(item);
Yes, it is possible. Already done.

2019-04-23 11:41 UTC, AntsiferauGodel approved these changes
Seems ok to me

2019-04-23 12:31 UTC, gennadybaranov requested changes
There are multiple "Why do we need this?" questions. I would like to get answers to be sure that everything is clear. :) Some of them probably don't need to be addressed.

2019-04-23 12:31 UTC, gennadybaranov commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +            context.Set<T>().Add(item);
Or `private readonly field`

2019-04-23 12:31 UTC, gennadybaranov commented on NugetAnalyzer.DAL/Interfaces/IRepository.cs
> +        void Update(T item);
Please add the following:
- GetByIdAsync
- GetSignleOrDefaultAsync(Func<T, bool> predicate)
- Make Get/GetAll Async

2019-04-23 12:31 UTC, gennadybaranov commented on NugetAnalyzer.DAL/Interfaces/IUnitOfWork.cs
> +        void SaveChanges();
Please make this Async

2019-04-23 12:31 UTC, gennadybaranov commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +            context.Entry(item).State = EntityState.Modified;
Why do we need this?  :)

2019-04-23 12:31 UTC, gennadybaranov commented on NugetAnalyzer/Startup.cs
> +            services.AddScoped(typeof(Repository<>), typeof(Repository<>));
Why do we need this? Are you going to inject directly repository?

2019-04-23 12:31 UTC, gennadybaranov commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +                .Where(predicate);
Why do we need `.AsEnumerable()` here?

2019-04-23 12:31 UTC, gennadybaranov commented on NugetAnalyzer.DAL/Interfaces/IRepository.cs
> +        IEnumerable<T> GetAll();
Why do we use IEnumerable here? Alternatives?

2019-04-23 12:51 UTC, pipalalala commented on NugetAnalyzer.DAL/Interfaces/IUnitOfWork.cs
> +        void SaveChanges();
Done

2019-04-23 12:55 UTC, pipalalala commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +                .Where(predicate);
Removed

2019-04-23 13:00 UTC, pipalalala commented on NugetAnalyzer.DAL/Interfaces/IRepository.cs
> +        IEnumerable<T> GetAll();
IReadOnlyCollection is using now

2019-04-23 13:14 UTC, gennadybaranov commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +                .Where(predicate);
Why was it removed? Why do ew leave it as IEnumerable?

2019-04-24 08:15 UTC, pipalalala commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +            context.Entry(item).State = EntityState.Modified;
context.Set<T>().Attach(item) was removed. Attach is used when you want to update only props that was changed, but EntityState.Modified updates all props of entity. It was used for reliability)

2019-04-24 08:19 UTC, pipalalala commented on NugetAnalyzer/Startup.cs
> +            services.AddScoped(typeof(Repository<>), typeof(Repository<>));
Removed, because I always return a new instance of repository.

2019-04-24 11:44 UTC, pipalalala commented on NugetAnalyzer.DAL/Interfaces/IRepository.cs
> +        void Update(T item);
All done

2019-04-24 11:48 UTC, pipalalala commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +                .Where(predicate);
Now we convert it to list. Then we use AsReadOnly() to convert list to IReadOnlyCollection

2019-04-24 11:51 UTC, pryabov requested changes

2019-04-24 11:51 UTC, pryabov commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +        public IEnumerable<T> GetAll()
`IEnumerable<T>` -> `IReadOnlyCollection` or `IReadOnlyList`

2019-04-24 11:51 UTC, pryabov commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +            return dbSet.AsNoTracking()
So left this? @gennadybaranov what do you think about it?

2019-04-24 11:51 UTC, pryabov commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +        public IEnumerable<T> Find(Func<T, bool> predicate)
In general, this method can return IQueryable but for me, it shouldn't be public. And for now, can be removed

2019-04-24 11:51 UTC, pryabov commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +            return await dbSet.AsNoTracking()
why not like this?
```
return await dbSet
    .AsNoTracking()
    .SingleOrDefaultAsync(predicates);
```

2019-04-24 11:51 UTC, pryabov commented on NugetAnalyzer.DAL/UnitOfWork/UnitOfWork.cs
> +            return new Repository<T>(context);
When repository will be disposed?

2019-04-25 07:34 UTC, gennadybaranov commented on NugetAnalyzer.DAL/UnitOfWork/UnitOfWork.cs
> +            return await context.SaveChangesAsync();
We don't need to add await here: please [read](https://www.tabsoverspaces.com/233659-do-not-await-what-does-not-need-to-be-awaited)

2019-04-25 07:38 UTC, gennadybaranov commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +            return list.AsReadOnly();
Why don't simply return list?

2019-04-25 07:50 UTC, pipalalala commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +            return await dbSet.AsNoTracking()
Resolved

2019-04-25 08:11 UTC, pipalalala commented on NugetAnalyzer.DAL/UnitOfWork/UnitOfWork.cs
> +            return new Repository<T>(context);
Remade: repository is created now by using serviceProvider

2019-04-25 08:12 UTC, pipalalala commented on NugetAnalyzer.DAL/UnitOfWork/UnitOfWork.cs
> +            return await context.SaveChangesAsync();
Yes, async/await were removed, but method remained asynchronous

2019-04-25 08:13 UTC, pipalalala commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +            return list.AsReadOnly();
Yes, list can be cast to IReadOnlyCollection without AsReadOnly()

2019-04-25 10:11 UTC, pipalalala commented on NugetAnalyzer.DAL/UnitOfWork/UnitOfWork.cs
> +            return await context.SaveChangesAsync();
Async/await were removed in some methods

2019-04-25 11:42 UTC, pryabov approved these changes

2019-04-26 08:24 UTC, HenadziBaranau approved these changes

2019-04-26 08:30 UTC, gennadybaranov approved these changes

2019-04-26 13:54 UTC, merged