Feature/18 base layout (#18)
AnyCase-Company-LTD/NugetAnalyzer pull request #29
Opened 2019-04-29 14:53 UTC by pipalalala

2019-04-30 07:22 UTC, maximKalinov requested changes

2019-04-30 07:22 UTC, maximKalinov commented on NugetAnalyzer/Views/Shared/_Layout.cshtml
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"
Please, change it to src="~/scripts/popper.min.js"

2019-04-30 07:26 UTC, maximKalinov approved these changes
Seems ok

2019-04-30 07:26 UTC, pipalalala commented on NugetAnalyzer/Views/Shared/_Layout.cshtml
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"
Done

2019-04-30 07:52 UTC, gennadybaranov requested changes

2019-04-30 07:52 UTC, gennadybaranov commented on NugetAnalyzer/Startup.cs
> +            app.UseStaticFiles();
Please read about middlewares order: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.2

2019-04-30 07:52 UTC, gennadybaranov commented on NugetAnalyzer/Controllers/HomeController.cs
> +using System.Threading.Tasks;
Unused usings

2019-04-30 07:52 UTC, gennadybaranov commented on NugetAnalyzer/NugetAnalyzer.csproj
> +    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.3" />
Do we really need this package?

2019-04-30 07:52 UTC, gennadybaranov commented on NugetAnalyzer/NugetAnalyzer.csproj
> +  </ItemGroup>
Looks strange. `<Content Remove.. />` above and this line

2019-04-30 07:52 UTC, gennadybaranov commented on NugetAnalyzer/Views/Shared/_Layout.cshtml
> +            <svg height="32" viewBox="0 0 16 16" version="1.1" width="32" aria-hidden="true">
Let's remove github logo from our templates

2019-04-30 07:52 UTC, gennadybaranov commented on NugetAnalyzer/Views/Shared/_Layout.cshtml
> +    <nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #24292e">
Try to avoid inline styles

2019-04-30 07:52 UTC, gennadybaranov commented on NugetAnalyzer/wwwroot/stylesheets/Shared/_Layout.css
> +﻿.navbar__logo svg {
Please make sure that we have only required files under source control. I think that we could only keep scss file, the rest could be excluded and probably added to .gitignore.

- do we need *.css file?
- do we need *.min.css file?

2019-04-30 07:52 UTC, gennadybaranov commented on NugetAnalyzer/wwwroot/stylesheets/Shared/_Layout.scss
> +    border-top: 1px solid rgba(0,0,0,.2);
- It makes sense to use [variables](https://sass-lang.com/guide) for colors, borders
 - try to avoid using id in styles. Prefer classes

2019-04-30 07:52 UTC, gennadybaranov commented on NugetAnalyzer/wwwroot/stylesheets/Shared/_Layout.scss
> +    border: none !important;
Do we really need to use `!important` everywhere?

2019-04-30 07:52 UTC, gennadybaranov commented on NugetAnalyzer/compilerconfig.json
> +  },
Can't find this styles.

2019-04-30 08:26 UTC, pipalalala commented on NugetAnalyzer/Startup.cs
> +            app.UseStaticFiles();
Thanks. It was moved after exception handling and before mvc

2019-04-30 08:29 UTC, pipalalala commented on NugetAnalyzer/Controllers/HomeController.cs
> +using System.Threading.Tasks;
Were removed

2019-04-30 08:30 UTC, pipalalala commented on NugetAnalyzer/NugetAnalyzer.csproj
> +    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.3" />
Yes, it used for compilation *.scss files

2019-04-30 08:54 UTC, pipalalala commented on NugetAnalyzer/wwwroot/stylesheets/Shared/_Layout.css
> +﻿.navbar__logo svg {
Okey, i'll add them to .gitignore

2019-04-30 09:06 UTC, pipalalala commented on NugetAnalyzer/wwwroot/stylesheets/Shared/_Layout.scss
> +    border: none !important;
Yes, it used for rewritng bootstrap styles

2019-04-30 09:07 UTC, pipalalala commented on NugetAnalyzer/compilerconfig.json
> +  },
![image](https://user-images.githubusercontent.com/42217149/56951426-8251f900-6b40-11e9-965b-5fa006286847.png)

2019-04-30 09:11 UTC, pipalalala commented on NugetAnalyzer/NugetAnalyzer.csproj
> +  </ItemGroup>
It's a code that the WebCompiler extension generates. I think it's necessary thing

2019-04-30 10:36 UTC, pipalalala commented on NugetAnalyzer/Views/Shared/_Layout.cshtml
> +            <svg height="32" viewBox="0 0 16 16" version="1.1" width="32" aria-hidden="true">
Logos were changed

2019-04-30 10:37 UTC, pipalalala commented on NugetAnalyzer/Views/Shared/_Layout.cshtml
> +    <nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #24292e">
They are moved to _Layout.scss

2019-04-30 10:37 UTC, pipalalala commented on NugetAnalyzer/wwwroot/stylesheets/Shared/_Layout.scss
> +    border-top: 1px solid rgba(0,0,0,.2);
ID's were changed to classes. Ok, i'll add variables .

2019-04-30 13:18 UTC, gennadybaranov commented on NugetAnalyzer/compilerconfig.json
> +  },
It's shared folder and mapping above:
```
"inputFile": "wwwroot/stylesheets/_Layout.scss"
```

2019-05-02 09:10 UTC, pipalalala commented on NugetAnalyzer/wwwroot/stylesheets/Shared/_Layout.css
> +﻿.navbar__logo svg {
Web Compiler can create css files on build

2019-05-02 09:11 UTC, pipalalala commented on NugetAnalyzer/compilerconfig.json
> +  },
Fixed

2019-05-02 10:41 UTC, pryabov commented on NugetAnalyzer/wwwroot/stylesheets/Shared/_Layout.css
> +﻿.navbar__logo svg {
Make sure that file created on Build and Publish

2019-05-02 10:43 UTC, pryabov commented on NugetAnalyzer/wwwroot/stylesheets/Shared/_Layout.css
> +﻿.navbar__logo svg {
add comments to the file and separate it to several sections

e.g.
```
// ----------- navbar ------------
// ----------- footer ------------
```

2019-05-02 10:44 UTC, pryabov commented on NugetAnalyzer/wwwroot/stylesheets/Shared/_Layout.css
> +  color: rgba(255, 255, 255, 0.7) !important; }
`}` should be on the next line @maximKalinov @pipalalala

2019-05-02 10:44 UTC, pryabov commented on NugetAnalyzer/wwwroot/stylesheets/Shared/_Layout.css
> +    outline: none !important;
`!important` remove it as many places as it is possible.

2019-05-02 11:54 UTC, gennadybaranov commented on NugetAnalyzer/wwwroot/stylesheets/Shared/_Layout.css
> +  color: rgba(255, 255, 255, 0.7) !important; }
This file is auto generated and will be removed.

2019-05-03 06:50 UTC, pipalalala commented on NugetAnalyzer/wwwroot/stylesheets/Shared/_Layout.css
> +﻿.navbar__logo svg {
Done

2019-05-03 06:54 UTC, pipalalala commented on NugetAnalyzer/wwwroot/stylesheets/Shared/_Layout.css
> +    outline: none !important;
They are all necessary

2019-05-03 08:26 UTC, gennadybaranov approved these changes

2019-05-03 08:38 UTC, merged