Nuget api service (#21)
AnyCase-Company-LTD/NugetAnalyzer pull request #32
Opened 2019-05-03 10:59 UTC by maximKalinov

2019-05-03 11:25 UTC, materiywakal approved these changes

2019-05-03 11:48 UTC, ArBond requested changes

2019-05-03 11:48 UTC, ArBond commented on NugetAnalyzer.BLL.Test/Services/NugetApiServiceTests.cs
> +            var packageVersion = await nugetApiService.GetLatestVersionPackageAsync("NUnit");
propose to do in the integration tests (another class)

2019-05-03 11:48 UTC, ArBond commented on NugetAnalyzer.BLL.Test/Services/NugetApiServiceTests.cs
> +            var packageVersion = await nugetApiService.GetLatestVersionPackageAsync("NUnit");
and add category to TestFixture attribute in all tests, "unit tests" for example

2019-05-03 11:48 UTC, ArBond commented on NugetAnalyzer.BLL.Test/Services/NugetServiceTests.cs
> +            };
duplication
define as a member of the class?

2019-05-03 11:48 UTC, ArBond commented on NugetAnalyzer.BLL/Services/NugetApiService.cs
> +                            "MM/dd/yyyy HH:mm:ss",
can be transferred to contacts?

2019-05-03 11:48 UTC, ArBond commented on NugetAnalyzer.BLL/Services/NugetService.cs
> +            this.nugetApiService = nugetApiService;
ArgumentNullException missing

2019-05-03 11:48 UTC, ArBond commented on NugetAnalyzer.BLL/Services/VersionService.cs
> +            this.uow = uow;
too

2019-05-03 11:48 UTC, ArBond commented on NugetAnalyzer.BLL/Services/NugetApiService.cs
> +            this.configuration = configuration;
ArgumentNullException missing

2019-05-03 12:24 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/NugetApiService.cs
> +            this.configuration = configuration;
Done

2019-05-03 12:24 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/VersionService.cs
> +            this.uow = uow;
Done

2019-05-03 12:24 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/NugetService.cs
> +            this.nugetApiService = nugetApiService;
Done

2019-05-03 12:40 UTC, maximKalinov commented on NugetAnalyzer.BLL.Test/Services/NugetServiceTests.cs
> +            };
For each method, this data must be its own

2019-05-03 13:15 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/NugetApiService.cs
> +                            "MM/dd/yyyy HH:mm:ss",
Done

2019-05-03 13:16 UTC, ArBond approved these changes

2019-05-06 07:42 UTC, maximKalinov commented on NugetAnalyzer.BLL.Test/Services/NugetApiServiceTests.cs
> +            var packageVersion = await nugetApiService.GetLatestVersionPackageAsync("NUnit");
I changed requests to mock server instead of requests to real NugetApi

2019-05-06 14:41 UTC, gennadybaranov submitted a review, later dismissed

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.DAL/Interfaces/IVersionRepository.cs
> +        Task<IReadOnlyCollection<PackageVersion>> GetLatestVersionAsync(Expression<Func<PackageVersion, bool>> predicate);
Please use empty line between method declarations. Fix `Version` to `Versions` - plural,

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.DAL/Interfaces/IUnitOfWork.cs
> +        IRepository<T> GetGenericRepository<T>()
No need to rename to `Generic`. Please revert these changes

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.DAL/Interfaces/IUnitOfWork.cs
> +            where T : IVersionRepository;
Why is it generic? We are returning repo of specific type. It could we property for such repos.

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.DAL/UnitOfWork/UnitOfWork.cs
>              return serviceProvider.GetRequiredService<IRepository<T>>();
Please make sure that this method will work with `PackageVersion`. And that would be awesome if you could refactor this so that `GetReposistory<PackageVersion>() == IVersionRepository`

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.Web/Startup.cs
> +            services.AddScoped<IDateTimeProvider, UtcDateTimeProvider>();
Could it be singleton?

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.Web/Startup.cs
> +            services.AddHttpClient();
Use typed client for NugetApiService

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.DAL/Repositories/VersionRepository.cs
> +                        .First())
Refactor duplication:
```
.Group()
.Select()
```

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +        protected readonly DbSet<T> dbSet;
Do we need both protected? How about using resharper naming convention? - protected member is upper-cased

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Utilities/UtcDateTimeProvider.cs
> +        public DateTime CurrentDateAndTime => DateTime.UtcNow;
Better `CurrentUtcDateTime`. Could be moved to .Common proj

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Services/NugetService.cs
> +            packageRepository = uow.GetGenericRepository<Package>();
Probably create separate `PackageService` instead of directly using uow here?

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.DAL/Repositories/VersionRepository.cs
> +                .ToListAsync();
AsNoTracking?

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Services/VersionService.cs
> +            await uow.SaveChangesAsync();
Copy and paste of previous method. Refactor

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Services/VersionService.cs
> +                var latestVersion = latestVersions.First(p => p.PackageId == packageVersion.PackageId);
Are we sure that First doesn't raise InvalidOperation?

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Services/NugetApiService.cs
> +            var url = $"{configuration["EndpointsNugetApi:PackageMetadata"]}/v3/registration3/{packageName.ToLowerInvariant()}/{version}.json";
Read about [Options](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2)

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Services/NugetApiService.cs
> +        private async Task<string> GetPackageMetadataAsync(string packageName, string version)
Please declare public methods first.

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Services/NugetApiService.cs
> +            return  await response.Content.ReadAsStringAsync();
How large could response be? It might be more efficient to use `Stream`

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Services/NugetApiService.cs
> +        public async Task<DateTime?> GetPublishedDateByVersionAsync(string packageName, string version)
Probably it makes more sense to return entire package metadata that contains all info about package instead of only publish date?

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Services/NugetApiService.cs
> +            var response = await client.SendAsync(request);
Do we need to handle errors from client? Timeout, NotFound, Cancelled?

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Services/NugetService.cs
> +            await versionService.UpdateLatestVersionOfNewPackagesAsync(versions);
Copy and paste. Refactor

2019-05-06 14:41 UTC, gennadybaranov commented on NugetAnalyzer.BLL.Test/Services/NugetServiceTests.cs
> +            versionServiceMock.Verify(x => x.UpdateLatestVersionOfNewPackagesAsync(It.IsAny<IEnumerable<PackageVersion>>()));
It's better to versify somehow that we are passing exactly those package versions which we expect base on response/repo mock (the same for other tests)

2019-05-07 05:59 UTC, pryabov requested changes
- Could you add task link to PR description as well? E.g. 
**Task:** #21 
- Also, rename PR too. In title should be in action not 3 nouns

2019-05-08 11:32 UTC, maximKalinov commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +        protected readonly DbSet<T> dbSet;
here I was mistaken NugetAnalyzerDbContext should be private.

2019-05-08 12:26 UTC, maximKalinov commented on NugetAnalyzer.DAL/Interfaces/IVersionRepository.cs
> +        Task<IReadOnlyCollection<PackageVersion>> GetLatestVersionAsync(Expression<Func<PackageVersion, bool>> predicate);
Done

2019-05-08 12:28 UTC, maximKalinov commented on NugetAnalyzer.Web/Startup.cs
> +            services.AddScoped<IDateTimeProvider, UtcDateTimeProvider>();
I think NugetApiService and UtcDateTimeProvider should be a singleton

2019-05-08 12:44 UTC, maximKalinov commented on NugetAnalyzer.DAL/Interfaces/IUnitOfWork.cs
> +        IRepository<T> GetGenericRepository<T>()
Done

2019-05-08 12:48 UTC, maximKalinov commented on NugetAnalyzer.DAL/Interfaces/IUnitOfWork.cs
> +            where T : IVersionRepository;
I fixed it. Now if you want to get IVersionRepository, you make (IVersionRepository)GetReposistory<PackageVersion>(); or refer to property VersionRepository of UoW

2019-05-08 12:48 UTC, maximKalinov commented on NugetAnalyzer.DAL/UnitOfWork/UnitOfWork.cs
>              return serviceProvider.GetRequiredService<IRepository<T>>();
Done

2019-05-08 12:49 UTC, maximKalinov commented on NugetAnalyzer.BLL/Utilities/UtcDateTimeProvider.cs
> +        public DateTime CurrentDateAndTime => DateTime.UtcNow;
Done

2019-05-08 13:14 UTC, maximKalinov commented on NugetAnalyzer.Web/Startup.cs
> +            services.AddHttpClient();
I used one typed client for 2 endpoints of NugetApiService, or I should use 2 different typed clients (classes)?

2019-05-08 13:26 UTC, maximKalinov commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +        protected readonly DbSet<T> dbSet;
I agree to use upper-cased for protected member

2019-05-08 13:28 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/NugetApiService.cs
> +        private async Task<string> GetPackageMetadataAsync(string packageName, string version)
Done

2019-05-10 09:22 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/NugetService.cs
> +            packageRepository = uow.GetGenericRepository<Package>();
Done

2019-05-10 09:27 UTC, maximKalinov commented on NugetAnalyzer.DAL/Repositories/VersionRepository.cs
> +                .ToListAsync();
I added AsNoTracking and the new Attach method in IRepository.

2019-05-10 09:28 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/VersionService.cs
> +            await uow.SaveChangesAsync();
Done

2019-05-10 09:51 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/VersionService.cs
> +                var latestVersion = latestVersions.First(p => p.PackageId == packageVersion.PackageId);
if First calls InvalidOperation, then we have an error in the application logic and need to be fixed during development

2019-05-10 09:54 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/NugetApiService.cs
> +            return  await response.Content.ReadAsStringAsync();
We do not have a large response. It is the size of about 2 KB

2019-05-10 09:55 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/NugetService.cs
> +            await versionService.UpdateLatestVersionOfNewPackagesAsync(versions);
Done

2019-05-13 12:42 UTC, pryabov requested changes

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL.Test/Services/NugetApiServiceTests.cs
> +            configuration = new ConfigurationBuilder()
Create Configuration service.

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL.Test/Services/NugetApiServiceTests.cs
> +            var response = await File.ReadAllTextAsync(Path.GetFullPath(configuration["EndpointSearch:NotExist:Response"]));
Obtain from configuration service. Do not hardcode long string keys

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL.Test/Services/NugetHttpServiceTests.cs
> +        const string EndpointSearch = "https://api-v2v3search-1.nuget.org";
why this comes not from configurations?

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL.Test/Services/NugetServiceTests.cs
> +            packageServiceMock.Verify(p => p.GetAllAsync());
what is `p`? Does it some kind of abbreviation? If yes then abbreviation of what?

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL/Interfaces/INugetApiService.cs
> +        Task<PackageVersion> GetLatestVersionPackageAsync(string packageName);
Incorrect words order.
`GetLatestPackageVersionAsync`

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL/Interfaces/INugetApiService.cs
> +        Task<DateTime?> GetPublishedDateByVersionAsync(string packageName, string version);
`GetPackagePublishedDateByVersionAsync`

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL/Interfaces/INugetHttpService.cs
> +        Task<string> GetDataOfPackageVersionAsync(string query);
What Data in this case means?

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL/Interfaces/INugetService.cs
> +        Task RefreshLatestVersionOfNewPackagesAsync();
Not clear. What does it mean `New`?

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL/Interfaces/INugetApiService.cs
> +    public interface INugetApiService
pls add a description for the purpose of this interface.
///<summary>
///</summary>
Can be used https://submain.com/products/ghostdoc.aspx

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL/Interfaces/IPackageService.cs
> +        Task<IReadOnlyCollection<Package>> GetNewPackagesAsync();
The same this is not clear what is `New` p[ackages

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL/Services/NugetApiService.cs
> +        public NugetApiService(INugetHttpService httpService)
Rename to `nugetHttpService`

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL/Services/NugetHttpService.cs
> +        public NugetHttpService(HttpClient client, IOptions<NugetSettings> options)
Rename `client` and `options`

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL/Services/NugetHttpService.cs
> +            }
Why in the same situation two different variants of how it is implemented?

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL/Services/NugetHttpService.cs
> +            return await response.Content.ReadAsStringAsync();
Do we need `async` there?

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL/Services/NugetHttpService.cs
> +            return await response.Content.ReadAsStringAsync();
`async`?

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL/Services/NugetService.cs
> +        private async Task<PackageVersion> GetLatestVersionOfPackageAsync(Package package)
How usage of this function impacted on the performance? Can we get rid of it?

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL/Services/PackageService.cs
> +        private readonly IRepository<Package> packageRepository;
Use Lazy here

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL/Services/VersionService.cs
> +                                                        .Select(x => x.PackageId)
What is `x`?

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.BLL/Services/VersionService.cs
> +                versionRepository.Attach(latestVersion);
`Attach` is it EF specific function? Should BL do it or this should be handled on DB access layer?

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.DAL/Helpers/GroupByExtension.cs
> +                .GroupBy(p => new { p.PackageId, p.Major, p.Minor, p.Build, p.Revision })
What is `p`?

2019-05-13 12:42 UTC, pryabov commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +        public void Attach(T item)
Usage of such method is bad practise. You expose EF functionality to other layers. FOr example for MongoDB driver there is no ability to attach to something.

2019-05-14 07:20 UTC, maximKalinov commented on NugetAnalyzer.BLL.Test/Services/NugetServiceTests.cs
> +            packageServiceMock.Verify(p => p.GetAllAsync());
"p" is a random variable. I think I’ll replace it on the first letter of a variable

2019-05-14 07:20 UTC, maximKalinov commented on NugetAnalyzer.BLL/Interfaces/INugetHttpService.cs
> +        Task<string> GetDataOfPackageVersionAsync(string query);
this is the metadata that is returned as a response from an endpoint of a search(authors, version, title, description etc)

2019-05-14 07:20 UTC, maximKalinov commented on NugetAnalyzer.BLL/Interfaces/INugetApiService.cs
> +        Task<PackageVersion> GetLatestVersionPackageAsync(string packageName);
I changed it to GetLatestPackageVersionAsync

2019-05-14 07:20 UTC, maximKalinov commented on NugetAnalyzer.BLL/Interfaces/INugetApiService.cs
> +        Task<DateTime?> GetPublishedDateByVersionAsync(string packageName, string version);
Done

2019-05-14 07:20 UTC, maximKalinov commented on NugetAnalyzer.BLL/Interfaces/INugetHttpService.cs
> +        Task<string> GetDataOfPackageVersionAsync(string query);
I'll rename both methods. The first in GetPackageVersionMetadataAsync that returns information about the specific version of the package, The second in GetPackageMetadataAsync that returns information about the whole package

2019-05-14 07:20 UTC, maximKalinov commented on NugetAnalyzer.BLL/Interfaces/INugetService.cs
> +        Task RefreshLatestVersionOfNewPackagesAsync();
New package means that the package added and not checked for the latest version of the package.
I rename it to RefreshLatestVersionOfNewlyAddedPackagesAsync () to make it more clear

2019-05-14 07:20 UTC, maximKalinov commented on NugetAnalyzer.BLL/Interfaces/IPackageService.cs
> +        Task<IReadOnlyCollection<Package>> GetNewPackagesAsync();
I renamed it to GetNewlyAddedPackagesAsync

2019-05-14 07:20 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/NugetApiService.cs
> +        public NugetApiService(INugetHttpService httpService)
Done

2019-05-14 07:20 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/NugetHttpService.cs
> +        public NugetHttpService(HttpClient client, IOptions<NugetSettings> options)
Done

2019-05-14 07:20 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/NugetHttpService.cs
> +            }
The situation is not the same here, in the first version I have a “client”, like field and parameter of one type, but in the second version, I have "nugetSettings" and "options" of different types. And "options" I use just in a constructor

2019-05-14 07:20 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/PackageService.cs
> +        private readonly IRepository<Package> packageRepository;
I made it using a property

2019-05-14 07:20 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/VersionService.cs
> +                                                        .Select(x => x.PackageId)
I changed it on a more clear argument

2019-05-14 07:20 UTC, maximKalinov commented on NugetAnalyzer.DAL/Helpers/GroupByExtension.cs
> +                .GroupBy(p => new { p.PackageId, p.Major, p.Minor, p.Build, p.Revision })
I changed it on a more clear argument

2019-05-14 07:20 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/NugetService.cs
> +        private async Task<PackageVersion> GetLatestVersionOfPackageAsync(Package package)
This reduces the time for getting responses from NetApi several times if we get many packages at once.

2019-05-14 08:47 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/VersionService.cs
> +                versionRepository.Attach(latestVersion);
Attach" is specific function of EF and it is not to be to BLL. I removed it from here. Now I update entities Package and PackageVersion usage method "Update" their Repositories

2019-05-14 13:12 UTC, maximKalinov commented on NugetAnalyzer.DAL/Repositories/VersionRepository.cs
> +                        .First())
Done

2019-05-14 15:53 UTC, pryabov requested changes

2019-05-14 15:53 UTC, pryabov commented on NugetAnalyzer.BLL.Test/Services/NugetServiceTests.cs
> +            packageServiceMock.Verify(p => p.GetAllAsync());
could you rename it to something sensible? I mean if type for example `MyType` variable name can be `myType`

2019-05-14 15:53 UTC, pryabov commented on NugetAnalyzer.BLL/Interfaces/INugetApiService.cs
> +    public interface INugetApiService
Better to write such comments in 3 lines
```
///`<summary>`
Used to work with Nuget API
///`</summary>`
```

2019-05-14 15:53 UTC, pryabov commented on NugetAnalyzer.BLL/Services/NugetHttpService.cs
> +            }
`(nugetSettings ?? throw new ArgumentNullException(nameof(nugetSettings))).Value;`
will this work?

2019-05-14 15:53 UTC, pryabov commented on NugetAnalyzer.BLL/Services/NugetService.cs
> +        private async Task<PackageVersion> GetLatestVersionOfPackageAsync(Package package)
Yep, understood, thank you

2019-05-15 08:52 UTC, maximKalinov commented on NugetAnalyzer.BLL/Interfaces/INugetApiService.cs
> +    public interface INugetApiService
Done

2019-05-15 08:52 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/NugetHttpService.cs
> +            }
Yes, it looks better. Done

2019-05-15 08:52 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/NugetHttpService.cs
> +            return await response.Content.ReadAsStringAsync();
Yes, because otherwise, we will return Task<Task<string>>

2019-05-15 09:00 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/NugetApiService.cs
> +        public async Task<DateTime?> GetPublishedDateByVersionAsync(string packageName, string version)
I think we should only return publish date, because package metadata contains specific information that we don’t need.

2019-05-15 10:42 UTC, pryabov approved these changes

2019-05-20 06:37 UTC, merged