Repository service (#22)
AnyCase-Company-LTD/NugetAnalyzer pull request #33
Opened 2019-05-08 11:25 UTC by pipalalala

RepositoryAnalyzerService was made. Also RepositoryService was made to

2019-05-09 15:01 UTC, gennadybaranov submitted a review, later dismissed
Directory/FileService could be moved to Common.

2019-05-09 15:01 UTC, gennadybaranov commented on NugetAnalyzer.Web/Startup.cs
> +            services.AddScoped<IRepositoryAnalyzerService, RepositoryAnalyzerService>();
Scoped vs Singleton?

2019-05-09 15:01 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Interfaces/IDirectoryService.cs
> +        void DeleteRepository(string repositoryPath);
Rename to `Delete(path)`

2019-05-09 15:01 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Interfaces/IDirectoryService.cs
> +        string CreateDirectoryForRepository();
DirectoryService should know only about directories. Rename to `Create(path)`

2019-05-09 15:01 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Interfaces/IDirectoryService.cs
> +        bool IsDirectoryExist(string repositoryPath);
`DoesDirectoryExist`? Argument - `directoryPath`

2019-05-09 15:01 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Interfaces/IFileService.cs
> +        string GetFileContent(string filePath);
Async

2019-05-09 15:01 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Interfaces/IFileService.cs
> +        string GetCsProjFilePath(string projectPath);
Remove `GetPackagesConfigFilePath` and `GetCsProjFilePath`. Could we use `GetFilesPaths` or create overloaded method?

2019-05-09 15:01 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Services/DirectoryService.cs
> +            stringBuilder.Append(Guid.NewGuid().ToString());
ToString could be removed.

The logic related to generation of path should be in service which invokes `CreateDirectory(path)`

2019-05-09 15:01 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +            return packages;
Strange empty lines at this method..

2019-05-09 15:01 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +            return packages;
Refactor methods `GetPackagesOfCoreApp` and `GetPackagesOfFrameworkApp` . They are identical. The only difference: `"//packages/package"` vs `"//Project/ItemGroup/PackageReference"`

2019-05-09 15:01 UTC, gennadybaranov commented on NugetAnalyzer.BLL/NugetAnalyzer.BLL.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.2.0" />
Do we need this?

2019-05-09 15:01 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Models/Solutions/Solution.cs
> +    public class Solution
Could we inherit Project, Repository, Solution from one 
```
class xxx 
{
   public string Name { get; }

   public string Path { get; }

  ctor(path, name)
  {
  } 
}
```
?

2019-05-09 15:01 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +        }
Think how to refactor methods.. they are almost identical. Probably recursion for analyzing directory and populating packages after.. or smth like this.

2019-05-10 07:40 UTC, pipalalala commented on NugetAnalyzer.BLL/Interfaces/IDirectoryService.cs
> +        void DeleteRepository(string repositoryPath);
Done

2019-05-10 07:49 UTC, pipalalala commented on NugetAnalyzer.BLL/Interfaces/IDirectoryService.cs
> +        string CreateDirectoryForRepository();
Was renamed to CreateDirectory(string path)

2019-05-10 07:58 UTC, pipalalala commented on NugetAnalyzer.BLL/Interfaces/IDirectoryService.cs
> +        bool IsDirectoryExist(string repositoryPath);
Traditionally when method checking something and returns bool type, it named like <Is>.... . I think it's better name for this method. But it will be rename to IsDirectoryExists. And i'll change argument to directoryPath of course.

2019-05-10 08:39 UTC, pipalalala commented on NugetAnalyzer.BLL/Interfaces/IFileService.cs
> +        string GetCsProjFilePath(string projectPath);
We can't use GetFilesPaths() because it always returns array of paths. But in case of GetPackagesConfigFilePath() and GetCsProjFilePath() we need to know if file exists. Those methods returns null and it's a part of logic. But I created GetFilePath(string directoryPath, string searchPattern), that replace GetPackagesConfigFilePath() and GetCsProjFilePath() methods.

2019-05-10 08:56 UTC, pipalalala commented on NugetAnalyzer.BLL/Services/DirectoryService.cs
> +            stringBuilder.Append(Guid.NewGuid().ToString());
Ok, all logic that includes paths generation were removed. It will be used in facade, sure.

2019-05-10 09:51 UTC, pipalalala commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +            return packages;
Refactoring was made. AddPackagesToPackagesListForCoreApp() and AddPackagesToPackagesListForFrameworkApp() were added anyway, because there are some difference in attribute searching in xmlNode too.

2019-05-10 09:53 UTC, pipalalala commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +            return packages;
Refactoring was made and they were removed.

2019-05-10 09:58 UTC, pipalalala commented on NugetAnalyzer.BLL/NugetAnalyzer.BLL.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.2.0" />
Now when we don't use paths generation, it can be removed. It was used for getting access to wwwroot directory path.

2019-05-10 10:00 UTC, pipalalala commented on NugetAnalyzer.BLL/NugetAnalyzer.BLL.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.2.0" />
UPD: removed

2019-05-10 10:49 UTC, pipalalala commented on NugetAnalyzer.BLL/Models/Solutions/Solution.cs
> +    public class Solution
Yes, why not, it's a good idea. Done, but I'm not sure if the name of the base class is correct. I really don't know how to name this base model.

2019-05-13 10:50 UTC, pipalalala commented on NugetAnalyzer.BLL/Interfaces/IFileService.cs
> +        string GetFileContent(string filePath);
Done

2019-05-13 10:53 UTC, pipalalala commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +            return packages;
During refactoring those lines were removed

2019-05-13 11:00 UTC, pipalalala commented on NugetAnalyzer.Web/Startup.cs
> +            services.AddScoped<IRepositoryAnalyzerService, RepositoryAnalyzerService>();
Singleton of course.

2019-05-15 15:46 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Interfaces/IDirectoryService.cs
> +        void DeleteRepository(string repositoryPath);
I would say, that `Delete` is better. Code usage:
```
ctor(IDirectoryService directoryService)
{
   
}

void Method()
{
directoryService.Create(path);
//directoryService.CreateDirectory(path); - 2 usage of word "directory"
}

```

2019-05-15 15:49 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Interfaces/IDirectoryService.cs
> +        bool IsDirectoryExist(string repositoryPath);
It's grammatically incorrect to use "IsDirectoryExists".

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members

Is, Can, Has are also allowed. It's better even to use the same one name  as Microsoft uses: `Exists`

2019-05-16 11:02 UTC, pipalalala commented on NugetAnalyzer.BLL/Interfaces/IDirectoryService.cs
> +        void DeleteRepository(string repositoryPath);
Ok, I'll rename Delete() and Create()

2019-05-16 11:03 UTC, pipalalala commented on NugetAnalyzer.BLL/Interfaces/IDirectoryService.cs
> +        bool IsDirectoryExist(string repositoryPath);
Done

2019-05-16 12:02 UTC, pryabov requested changes

2019-05-16 12:02 UTC, pryabov commented on NugetAnalyzer.BLL.Test/Services/RepositoryAnalyzerServiceTests.cs
> +            directoryService.Setup(s => s.IsDirectoryExists(NullRepositoryPath)).Throws(new ArgumentNullException());
`s` change to more readable name

2019-05-16 12:02 UTC, pryabov commented on NugetAnalyzer.BLL.Test/Services/RepositoryAnalyzerServiceTests.cs
> +        private const string NullRepositoryPath = null;
Not sure if we need constant here. Can it be moved inside the method where it is used?

2019-05-16 12:02 UTC, pryabov commented on NugetAnalyzer.BLL/Models/BaseModel.cs
> +    public class BaseModel
Not clear naming. `BaseModel` of what?

2019-05-16 12:02 UTC, pryabov commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +            Core,
Should be:
```
private enum FrameworkType
        {
NotSpecified = 0,            
Core = 1,
etc.
```

2019-05-16 12:02 UTC, pryabov commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +            if (!directoryService.Exists(repositoryPath))
need `{` and `}`

2019-05-16 12:02 UTC, pryabov commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +        private XmlNodeList GetXmlNodeList(XmlDocument document, FrameworkType frameworkType)
Pls rename. Method name should match to the it purpose.

2019-05-16 13:11 UTC, pipalalala commented on NugetAnalyzer.BLL.Test/Services/RepositoryAnalyzerServiceTests.cs
> +            directoryService.Setup(s => s.IsDirectoryExists(NullRepositoryPath)).Throws(new ArgumentNullException());
Ok, no problem

2019-05-16 13:14 UTC, AntsiferauGodel requested changes

2019-05-16 13:14 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +            unitOfWork.SaveChangesAsync();
await?

2019-05-16 13:14 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +            Version.TryParse(version, out packageVersion);
out var?

2019-05-16 13:14 UTC, AntsiferauGodel commented on NugetAnalyzer.Common/Services/FileService.cs
> +                FileInfo file = new FileInfo(filePath);
var?

2019-05-16 13:14 UTC, AntsiferauGodel commented on NugetAnalyzer.Common/Services/FileService.cs
> +            IList<string> directoriesPaths = new List<string>();
var?

2019-05-16 13:14 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/Views/Home/Index.cshtml
> +﻿<link href="stylesheets/Home/Index.css" rel="stylesheet" />
I hope we will move it to section later..

2019-05-16 13:14 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/wwwroot/stylesheets/Home/Index.scss
> +    background-color: #24292e;
use a variable for colors?

2019-05-16 13:16 UTC, pipalalala commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +            Core,
Done

2019-05-16 13:19 UTC, pipalalala commented on NugetAnalyzer.BLL.Test/Services/RepositoryAnalyzerServiceTests.cs
> +        private const string NullRepositoryPath = null;
Yes. Done.

2019-05-16 13:30 UTC, pipalalala commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +            if (!directoryService.Exists(repositoryPath))
Done

2019-05-16 13:31 UTC, pipalalala commented on NugetAnalyzer.Common/Services/FileService.cs
> +            IList<string> directoriesPaths = new List<string>();
Done

2019-05-16 13:32 UTC, pipalalala commented on NugetAnalyzer.Common/Services/FileService.cs
> +                FileInfo file = new FileInfo(filePath);
Was changed to var

2019-05-16 13:35 UTC, pipalalala commented on NugetAnalyzer.Web/wwwroot/stylesheets/Home/Index.scss
> +    background-color: #24292e;
okeeeeeey

2019-05-16 13:36 UTC, pipalalala commented on NugetAnalyzer.Web/Views/Home/Index.cshtml
> +﻿<link href="stylesheets/Home/Index.css" rel="stylesheet" />
I hope too

2019-05-16 13:37 UTC, materiywakal commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +            unitOfWork.SaveChangesAsync();
nope

2019-05-16 13:37 UTC, materiywakal commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +            Version.TryParse(version, out packageVersion);
yep

2019-05-16 13:41 UTC, pipalalala commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +        private XmlNodeList GetXmlNodeList(XmlDocument document, FrameworkType frameworkType)
This method returns XmlNodeList, and it's obvious that it must be named as GetXmlNodeList

2019-05-16 13:55 UTC, pipalalala commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +            Version.TryParse(version, out packageVersion);
done

2019-05-16 14:02 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +            {
Please use var

2019-05-16 14:02 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +                var filePath = fileService.GetFilePath(project.Path, "packages.config");
Maybe you should use constants

2019-05-16 14:02 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +        public async Task SaveAsync(Models.Repositories.Repository repository, int userId)
Maybe use  aliases

2019-05-16 14:02 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +                Solutions = new List<Solution>()
it may make sense to do this in the class constructor

2019-05-16 14:14 UTC, pipalalala commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +            {
okey

2019-05-16 14:16 UTC, pipalalala commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +                var filePath = fileService.GetFilePath(project.Path, "packages.config");
Done

2019-05-16 14:19 UTC, pipalalala commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +        public async Task SaveAsync(Models.Repositories.Repository repository, int userId)
no

2019-05-16 14:20 UTC, AntsiferauGodel requested changes

2019-05-16 14:20 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL.Test/Services/RepositoryAnalyzerServiceTests.cs
> +            @"C:\temp\solution"
maybe use constants here too?

2019-05-16 14:20 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +            unitOfWork.SaveChangesAsync();
Why?

2019-05-16 14:20 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +                tempPackageVersion = await PackageVersionRepository.GetSingleOrDefaultAsync(dbPackageVersion =>
looks scary, think about moving this expression into separate variable

2019-05-16 14:20 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +                        if (tempPackageVersion.Package.Name == name &&
same as above

2019-05-16 14:23 UTC, pipalalala commented on NugetAnalyzer.BLL.Test/Services/RepositoryAnalyzerServiceTests.cs
> +            @"C:\temp\solution"
okey. no problem

2019-05-16 14:24 UTC, materiywakal commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +            unitOfWork.SaveChangesAsync();
Because i want to save data in db as parallel task.

2019-05-16 14:24 UTC, materiywakal commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +        public async Task SaveAsync(Models.Repositories.Repository repository, int userId)
Is it look so bad?

2019-05-16 14:25 UTC, materiywakal commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +                Solutions = new List<Solution>()
Seems good to me.

2019-05-16 14:28 UTC, materiywakal commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +                tempPackageVersion = await PackageVersionRepository.GetSingleOrDefaultAsync(dbPackageVersion =>
This code give us clear picture what exactly we are waiting for from db. Adding variables may make it difficult i think.

2019-05-16 14:28 UTC, materiywakal commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +                        if (tempPackageVersion.Package.Name == name &&
same as above

2019-05-16 14:46 UTC, pipalalala commented on NugetAnalyzer.BLL/Models/BaseModel.cs
> +    public class BaseModel
was renamed to BaseRepositoryModel

2019-05-16 18:03 UTC, pryabov commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +        private XmlNodeList GetXmlNodeList(XmlDocument document, FrameworkType frameworkType)
Nope. right question is `XmlNodeList of what?`

2019-05-17 08:18 UTC, pipalalala commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +        private XmlNodeList GetXmlNodeList(XmlDocument document, FrameworkType frameworkType)
Was renamed to GetXmlNodeListWithPackagesOfXmlDocument()

2019-05-17 08:28 UTC, pipalalala commented on NugetAnalyzer.BLL/Services/RepositoryAnalyzerService.cs
> +            if (!directoryService.Exists(repositoryPath))
I don't know how it works, but:
![image](https://user-images.githubusercontent.com/42217149/57914203-e857b380-7896-11e9-93fa-74cab24f48b2.png)

2019-05-17 14:57 UTC, pryabov approved these changes

2019-05-17 15:04 UTC, AntsiferauGodel approved these changes

2019-05-17 15:04 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +                Versions = new List<PackageVersion>()
ctor?

2019-05-17 15:04 UTC, AntsiferauGodel commented on NugetAnalyzer.Common/Services/FileService.cs
> +            return filesPaths.Count() == 0 ? null : filesPaths[0];
First() ?

2019-05-17 15:10 UTC, merged