Implement authentication flow (#13)
AnyCase-Company-LTD/NugetAnalyzer pull request #34
Opened 2019-05-08 11:51 UTC by AntsiferauGodel

Task: #13 
If you want to run the app, you should ask me for credentials(I store them in secrets.json). Or you can use your own.

2019-05-08 15:05 UTC, maximKalinov commented on NugetAnalyzer.DAL/Repositories/UserRepository.cs
> +            return DbSet.Where(p => p.GitHubId == gitHubId).Select(p => p.GitHubToken).FirstOrDefault();
Please do it like
DbSet
.Where(p => p.GitHubId == gitHubId)
.Select(p => p.GitHubToken)
.FirstOrDefault();

2019-05-08 15:05 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/UserService.cs
> +            var user = usersRepository.GetSingleOrDefaultAsync(p => p.UserName == userName).Result;
Please use await keyword instead of *.Result

2019-05-08 15:05 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/UserService.cs
> +            var user = usersRepository.GetSingleOrDefaultAsync(p => p.GitHubId == gitHubId).Result;
Please use await keyword instead of *.Result

2019-05-08 15:05 UTC, maximKalinov commented on NugetAnalyzer.BLL.Test/Services/UserServiceTests.cs
> +
Please delete the extra line

2019-05-08 15:10 UTC, maximKalinov commented on NugetAnalyzer.Web/Controllers/AccountController.cs
> +                var gitHubToken = HttpContext.GetTokenAsync("access_token").Result;
Please use await keyword instead of *.Result

2019-05-08 15:16 UTC, maximKalinov commented on NugetAnalyzer.Web/Controllers/AccountController.cs
> +                var gitHubToken = HttpContext.GetTokenAsync("access_token").Result;
could make "access_token" constant?

2019-05-08 15:19 UTC, maximKalinov commented on NugetAnalyzer.Web/Controllers/AccountController.cs
> +            int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out int userGitHubId);
Please use "out var userGitHubId" instead of "out int userGitHubId"

2019-05-08 15:28 UTC, maximKalinov commented on NugetAnalyzer.Web/Controllers/AccountController.cs
> +            int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out int userGitHubId);
Why do you not check what returns TryParse?

2019-05-08 15:28 UTC, maximKalinov commented on NugetAnalyzer.Web/ServiceCollectionExtensions/GitHubOAuthExtension.cs
> +               options.CallbackPath = userSecrets.GetSection("CallbackPath").Value;
Maybe it makes sense to use Options

2019-05-09 10:43 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/Controllers/AccountController.cs
> +            int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier), out int userGitHubId);
why var?

2019-05-09 13:49 UTC, gennadybaranov submitted a review, later dismissed
There is an issue with ports. Can't debug properly as getting 404 after login on github. Please make sure that correct port is specified in launchSettings.json and registered on GitHub.

Please make sure that [Authorize] attribute is used everywhere where it should be used

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/wwwroot/stylesheets/Shared/_Layout.scss
> +.nav__link_layout:hover {
_layout? Looks strange.. what did you mean?

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/wwwroot/stylesheets/Shared/SignIn.scss
> +.footer__link{
FYI: Saas supports nesting, but we will keep as it is to be more readable

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/wwwroot/stylesheets/Shared/SignIn.scss
> +﻿$backgroundColor: #f9f9f9;
It might be better to move it to separate colors.scss and include colors where necessary

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/Views/Account/UserCreationForm.cshtml
> +
Extra empty line

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/Controllers/AccountController.cs
> +using Microsoft.AspNetCore.Http;
Unused using

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.DAL/Migrations/20190503114542_UserUpdate.cs
> +    public partial class UserUpdate : Migration
Let's have an agreement, that one task shouldn't have more than 1 migration. We will get pretty much very quickly if create after each change

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.DAL/Interfaces/IUserRepository.cs
> +        string GetGitHubTokenByGitHubId(int gitHubId);
Let's make it Async. Does it make sense to retrieve user, not only GitHubToken?

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Domain/User.cs
> +        public string GitHubToken { get; set; }
I would suggest to move github specific properties to separate table/class. So, we will have 1-to-many for User-Profile. And 1-to-many for Source-Profile

Could we even unify props like below. I assume that gitlab, tfs should contain smth similar? Could we create a separate table Source with supported source controls: `1 - GitHub, 2 - ... `, etc?

```
//Profile.cs
public class Profile
{
        public int Id {get;set;}      

        public int UserId {get;set;}      

        public string AvatarUrl { get; set; }

        public string ProfileUrl { get; set; }

        public int ProfileId { get; set; }

        public string AccessToken { get; set; }

        public int SourceId { get; set; }
}
```

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Interfaces/IUserService.cs
> +        Profile GetProfileByGitHubId(int gitHubId);
Empty line above

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/ServiceCollectionExtensions/GitHubOAuthExtension.cs
> +        public static void AddGitHubOAuth(this IServiceCollection services, IConfigurationSection GitHubEndPoints, IConfigurationSection userSecrets)
`GitHubEndPoints` should be lower cased.

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/Startup.cs
> +                                .AddUserSecrets<Startup>()
That's awesome. But really good practice is to not use secrets for development mode. Currently, when I pull your branch, I should manually create secret on my dev machine and find somewhere required values. So, think about overwriting appSettings.Development.json and storing even secrets for dev there.

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/ServiceCollectionExtensions/GitHubOAuthExtension.cs
> +                       var user = JObject.Parse(await response.Content.ReadAsStringAsync());
Please don't inline method call as argument. It's impossible to debug then. It's better to split

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/Controllers/GitHubAuthController.cs
> +                AvatarUrl = User.FindFirstValue("urn:github:avatar")
Move claim names to constants as they are reused in several places.

Do we have access to `HttpContext.GetTokenAsync("access_token")`? Initialize it if possible.

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/Views/OAuthSignIn/SourceChoice.cshtml
> +            <svg height="64" viewBox="0 0 16 16" version="1.1" width="64" aria-hidden="true">
The same as above

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/Views/Account/UserCreationForm.cshtml
> +                <div>UserName</div>
Think about localization/resources files.

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/Controllers/AccountController.cs
> +                var gitHubToken = HttpContext.GetTokenAsync("access_token").Result;
Read about possible [deadlocks](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html) and share with guys

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/Views/Account/UserCreationForm.cshtml
> +                <a asp-controller="Home" asp-action="Index" class="mb-4">
Use html helper with logo created by @pipalalala

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/Views/Account/Profile.cshtml
> +            <img class="profile__column_item" src=@Model.AvatarUrl width="230px" height="230px"/>
Don't use inline, move to css classes

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Models/Profile.cs
> +        public int GitHubId { get; set; }
Depends on comment related to model unification, table for sources, etc, could be changes

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/Controllers/AccountController.cs
> +        public async Task<IActionResult> GitHubLogin(Profile profile)
Put correct attribute: get/post

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/Controllers/AccountController.cs
> +        public IActionResult UserCreationForm(Profile profile)
Should have [Authorize]?

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/Controllers/AccountController.cs
> +        public AccountController(IUserService userService)
Empty line above

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Models/Profile.cs
> +    public class Profile
I believe that it's DTO/viewModel. Let's add ViewModel as postfix. And let's keep viewModels and converters in separate project

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Converters/UserConverter.cs
> +    internal class UserConverter
Let's make public and test

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Interfaces/IUserService.cs
> +        string GetGitHubTokenByGitHubId(int gitHubId);
Also, depends on decision with profile, source tables will be name changes - without `GitHub`

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.Web/Controllers/AccountController.cs
> +            await userService.CreateUserAsync(profile, gitHubToken);
Think about moving stuff like `HttpContext.GetTokenAsync` to separate class `TokenProvider` that uses HttpContextAccessor. 

Think about injecting `TokenProvider` to `UserService`?

Let's return profile from `userService.CreateUserAsync` instead of line below.

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Interfaces/IUserService.cs
> +        Task CreateUserAsync(Profile profile, string gitHubToken);
I would say, that only `Profile` should be passed. See comments below

2019-05-09 13:49 UTC, gennadybaranov commented on NugetAnalyzer.BLL/Interfaces/IUserService.cs
> +        Task UpdateGitHubToken(int gitHubId, string gitHubToken);
Check that method has name `Async`.

I would say it should be `UpdateUserAsync(Profile)`

2019-05-10 08:38 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/wwwroot/stylesheets/Shared/_Layout.scss
> +.nav__link_layout:hover {
my bad, was renamed to  nav__link_navbar. I mean its custom nav-links for the navbar.

2019-05-10 08:39 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/wwwroot/stylesheets/Shared/SignIn.scss
> +.footer__link{
Thanks for the information

2019-05-10 08:42 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/Views/Account/UserCreationForm.cshtml
> +
removed, thanks

2019-05-10 08:44 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/Controllers/AccountController.cs
> +using Microsoft.AspNetCore.Http;
Removed, thanks

2019-05-10 08:48 UTC, AntsiferauGodel commented on NugetAnalyzer.DAL/Interfaces/IUserRepository.cs
> +        string GetGitHubTokenByGitHubId(int gitHubId);
Then I don't need this repo. I was thinking that returning users with his gitHub tokens was unsecure and that we need a separate method for pulling token. Seems I'm was wrong

2019-05-10 09:04 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/Startup.cs
> +                                .AddUserSecrets<Startup>()
I thought that that's a "true way" - you either use your own secrets, or you ask me to send you them via something. I mean somebody could steal our keys and etc...

2019-05-10 09:30 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/Views/Account/Profile.cshtml
> +            <img class="profile__column_item" src=@Model.AvatarUrl width="230px" height="230px"/>
done

2019-05-11 06:37 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/wwwroot/stylesheets/Shared/SignIn.scss
> +﻿$backgroundColor: #f9f9f9;
The thing is - "f9f9" color is only on the sign in page. And there is "ffff" color on the profile page. I'm talking about GitHub, which design we are copying ;)

2019-05-11 06:38 UTC, AntsiferauGodel commented on NugetAnalyzer.DAL/Migrations/20190503114542_UserUpdate.cs
> +    public partial class UserUpdate : Migration
Sure,  the will be only one migration after I finish with source control tables

2019-05-11 06:46 UTC, AntsiferauGodel commented on NugetAnalyzer.Domain/User.cs
> +        public string GitHubToken { get; set; }
Good idea! I'm working on it now.

2019-05-12 16:41 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/Controllers/GitHubAuthController.cs
> +                AvatarUrl = User.FindFirstValue("urn:github:avatar")
Done

2019-05-12 19:28 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/ServiceCollectionExtensions/GitHubOAuthExtension.cs
> +                       var user = JObject.Parse(await response.Content.ReadAsStringAsync());
fixed, thx

2019-05-12 19:29 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/Views/Account/UserCreationForm.cshtml
> +                <div>UserName</div>
done

2019-05-12 19:29 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/Controllers/AccountController.cs
> +        public AccountController(IUserService userService)
fixed, thx

2019-05-12 19:31 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Interfaces/IUserService.cs
> +        Task UpdateGitHubToken(int gitHubId, string gitHubToken);
fixed

2019-05-12 19:31 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Interfaces/IUserService.cs
> +        Task CreateUserAsync(Profile profile, string gitHubToken);
fixed

2019-05-13 06:17 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/Startup.cs
> +                                .AddUserSecrets<Startup>()
Done, anyway

2019-05-13 06:18 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/Controllers/AccountController.cs
> +        public async Task<IActionResult> GitHubLogin(Profile profile)
Done

2019-05-13 06:18 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/Controllers/AccountController.cs
> +        public IActionResult UserCreationForm(Profile profile)
Whole Controller now Authorize, thx

2019-05-13 06:31 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Models/Profile.cs
> +    public class Profile
Moved, thx

2019-05-13 06:31 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Converters/UserConverter.cs
> +    internal class UserConverter
Public now

2019-05-14 13:32 UTC, materiywakal approved these changes

2019-05-15 15:04 UTC, HenadziBaranau requested changes

2019-05-15 15:04 UTC, HenadziBaranau commented on NugetAnalyzer.BLL/Interfaces/ISourceService.cs
> +        Task<ICollection<SourceViewModel>> GetSourceList();
Async?

2019-05-15 15:04 UTC, HenadziBaranau commented on NugetAnalyzer.BLL/Services/ProfileService.cs
> +            profilesRepository = unitOfWork.GetRepository<Profile>();
Similar comment that Pavel suggested. Retrieve repository directly in method to avoid creating connection string in constructor.

2019-05-15 15:04 UTC, HenadziBaranau commented on NugetAnalyzer.DAL/UnitOfWork/UnitOfWork.cs
> +using NugetAnalyzer.Domain;
Unused

2019-05-15 15:04 UTC, HenadziBaranau commented on NugetAnalyzer.Dtos/Converters/UserConverter.cs
> +            //TODO: REFACTOR
When are we going to refactor this? :)

Think about combining converters with viewmodels instead of just 2 folders: "converters/models"

2019-05-15 15:04 UTC, HenadziBaranau commented on NugetAnalyzer.BLL/Services/ProfileService.cs
> +            return ProfileConverter.ConvertProfileToViewModel(profile);
Let's inject mappers instead of using static stuff?

2019-05-15 15:04 UTC, HenadziBaranau commented on NugetAnalyzer.Web/Controllers/AccountController.cs
> +            if (user == null)
TOO muck logic here and in method GitHubLogin. Needs refactoring like:
```
var profile = await UpdateAccessTokenIfExistAsync();
if (profile != null){

}

redirect()
```

2019-05-15 15:04 UTC, HenadziBaranau commented on NugetAnalyzer.Web/Controllers/GitHubAuthController.cs
> +            var accessToken = await HttpContext.GetTokenAsync(AccessTokenName);
Check please best practices for HttpContext vs IHttpContextAccessor. Probably use it instead. 

The same one for User in Controller.

Also a lot logic in controller.

2019-05-16 07:18 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Interfaces/ISourceService.cs
> +        Task<ICollection<SourceViewModel>> GetSourceList();
Oops, fixed, thx)

2019-05-16 07:33 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Services/ProfileService.cs
> +            profilesRepository = unitOfWork.GetRepository<Profile>();
fixed

2019-05-16 07:34 UTC, AntsiferauGodel commented on NugetAnalyzer.DAL/UnitOfWork/UnitOfWork.cs
> +using NugetAnalyzer.Domain;
removed, thx

2019-05-16 07:58 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Services/ProfileService.cs
> +            return ProfileConverter.ConvertProfileToViewModel(profile);
done

2019-05-16 08:08 UTC, AntsiferauGodel commented on NugetAnalyzer.Dtos/Converters/UserConverter.cs
> +            //TODO: REFACTOR
Do you mean like keep them in the root folder or put converters into view models? If the seconds one - why?

2019-05-17 14:07 UTC, pryabov approved these changes

2019-05-17 14:33 UTC, merged