Comparer service(#19)
AnyCase-Company-LTD/NugetAnalyzer pull request #35
Opened 2019-05-13 10:11 UTC by ArBond

2019-05-13 13:12 UTC, AntsiferauGodel requested changes
Some small notes

2019-05-13 13:12 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Converters/ProjectConverter.cs
> +    public class ProjectConverter
why not static?

2019-05-13 13:12 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Converters/RepositoryConverter.cs
> +    public class RepositoryConverter
same here

2019-05-13 13:12 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Converters/RepositoryConverter.cs
> +                    Solutions = repository.Solutions.Select(SolutionConverter.SolutionToSolutionWithVersionReport).ToList()
Too many dots in a row... and what if Solutions is null?

2019-05-13 13:12 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Converters/SolutionConverter.cs
> +                    Projects = solution.Projects.Select(ProjectConverter.ProjectToProjectWithVersionReport).ToList()
same here

2019-05-13 13:12 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL/Services/VersionAnalyzerService.cs
> +            return dateTimeProvider.CurrentUtcDateTime.Subtract(publishedDateOfLatestVersion.Value).Days / daysInTheMonth >=
too many dots i guess

2019-05-13 13:12 UTC, AntsiferauGodel commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +        protected readonly NugetAnalyzerDbContext context;
I guess you can leave context as private

2019-05-13 13:23 UTC, ArBond commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +        protected readonly NugetAnalyzerDbContext context;
done

2019-05-13 13:23 UTC, ArBond commented on NugetAnalyzer.BLL/Converters/RepositoryConverter.cs
> +    public class RepositoryConverter
done

2019-05-13 13:23 UTC, ArBond commented on NugetAnalyzer.BLL/Converters/ProjectConverter.cs
> +    public class ProjectConverter
done

2019-05-13 13:37 UTC, ArBond commented on NugetAnalyzer.BLL/Converters/RepositoryConverter.cs
> +                    Solutions = repository.Solutions.Select(SolutionConverter.SolutionToSolutionWithVersionReport).ToList()
done

2019-05-13 13:37 UTC, ArBond commented on NugetAnalyzer.BLL/Converters/SolutionConverter.cs
> +                    Projects = solution.Projects.Select(ProjectConverter.ProjectToProjectWithVersionReport).ToList()
done

2019-05-13 13:41 UTC, ArBond commented on NugetAnalyzer.BLL/Services/VersionAnalyzerService.cs
> +            return dateTimeProvider.CurrentUtcDateTime.Subtract(publishedDateOfLatestVersion.Value).Days / daysInTheMonth >=
done

2019-05-13 14:18 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/VersionAnalyzerService.cs
> +                return packageVersionConfiguration.VersionStatus.Revision;
Please, use braces

2019-05-13 14:18 UTC, maximKalinov commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +        protected readonly DbSet<T> dbSet;
Please, write protected member is upper-cased

2019-05-13 14:18 UTC, maximKalinov commented on NugetAnalyzer.DAL/UnitOfWork/UnitOfWork.cs
> +        public IRepositoryRepository RepositoryRepository => (IRepositoryRepository)GetRepository<Repository>();
I think this property needs to be removed and get the generic repository as before

2019-05-13 14:18 UTC, maximKalinov commented on NugetAnalyzer.DAL/UnitOfWork/UnitOfWork.cs
> +        public IVersionRepository VersionRepository => (IVersionRepository)GetRepository<PackageVersion>();
Please check this code I think you get an error

2019-05-13 14:18 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +                            packageIds.Add(projectPackageVersion.PackageVersion.PackageId);
Maybe it makes sense to refactor

2019-05-13 14:22 UTC, ArBond commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +                            packageIds.Add(projectPackageVersion.PackageVersion.PackageId);
how?

2019-05-13 14:23 UTC, maximKalinov commented on NugetAnalyzer.Web/Startup.cs
Please add  services.AddScoped(
                typeof(IRepository<PackageVersion>),
                provider => provider.GetService<IVersionRepository>());

2019-05-13 14:32 UTC, ArBond commented on NugetAnalyzer.DAL/Repositories/Repository.cs
> +        protected readonly DbSet<T> dbSet;
done

2019-05-13 14:55 UTC, ArBond commented on NugetAnalyzer.BLL/Services/VersionAnalyzerService.cs
> +                return packageVersionConfiguration.VersionStatus.Revision;
done

2019-05-13 14:55 UTC, ArBond commented on NugetAnalyzer.DAL/UnitOfWork/UnitOfWork.cs
> +        public IVersionRepository VersionRepository => (IVersionRepository)GetRepository<PackageVersion>();
nope =)

2019-05-13 14:56 UTC, ArBond commented on NugetAnalyzer.DAL/UnitOfWork/UnitOfWork.cs
> +        public IRepositoryRepository RepositoryRepository => (IRepositoryRepository)GetRepository<Repository>();
added definition to IUnitOfWotk

2019-05-13 14:58 UTC, AntsiferauGodel requested changes
Change test names

2019-05-13 14:58 UTC, AntsiferauGodel commented on NugetAnalyzer.BLL.Test/Services/RepositoryServiceTests.cs
> +        public void Constructor_Check_AllNullArgumentsThrowsArgumentNullException()
please rename your's tests with "should" and "when", see @maximKalinov  tests for example

2019-05-13 15:14 UTC, ArBond commented on NugetAnalyzer.DAL/UnitOfWork/UnitOfWork.cs
> +        public IVersionRepository VersionRepository => (IVersionRepository)GetRepository<PackageVersion>();
fixed in startup.cs

2019-05-13 15:14 UTC, ArBond commented on NugetAnalyzer.Web/Startup.cs
done

2019-05-13 15:24 UTC, ArBond commented on NugetAnalyzer.BLL.Test/Services/RepositoryServiceTests.cs
> +        public void Constructor_Check_AllNullArgumentsThrowsArgumentNullException()
done

2019-05-13 15:48 UTC, AntsiferauGodel approved these changes

2019-05-13 16:07 UTC, maximKalinov approved these changes

2019-05-13 16:08 UTC, maximKalinov approved these changes

2019-05-14 13:31 UTC, materiywakal approved these changes

2019-05-16 17:28 UTC, pryabov requested changes

2019-05-16 17:28 UTC, pryabov commented on NugetAnalyzer.Web/Controllers/HomeController.cs
> +            var result = await repositoryService.GetAnalyzedRepositoriesAsync(repository => repository.UserId == 1);
`result` not used

2019-05-16 17:28 UTC, pryabov commented on NugetAnalyzer.BLL/IOptions/PackageVersionAnalysisRules.cs
> +namespace NugetAnalyzer.BLL.IOptions
Rename folder and namespace. It shouldn't be `IOptions` It can be Configurations.
Filename also should be changed.
Better to move to a separate project which can be called `NugetAnalyzer.Common`

2019-05-16 17:47 UTC, pryabov requested changes

2019-05-16 17:47 UTC, pryabov commented on NugetAnalyzer.DAL/Interfaces/IVersionRepository.cs
> +        Task<IReadOnlyCollection<PackageVersion>> GetLatestPackageVersionsAsync(ICollection<int> packageIds);
There can be better to return Dictionary

2019-05-17 08:18 UTC, ArBond commented on NugetAnalyzer.Web/Controllers/HomeController.cs
> +            var result = await repositoryService.GetAnalyzedRepositoriesAsync(repository => repository.UserId == 1);
this is a test method call.
checked that everything is injected and returned

2019-05-17 08:31 UTC, ArBond commented on NugetAnalyzer.BLL/IOptions/PackageVersionAnalysisRules.cs
> +namespace NugetAnalyzer.BLL.IOptions
done

2019-05-17 08:47 UTC, ArBond commented on NugetAnalyzer.Web/Controllers/HomeController.cs
> +            var result = await repositoryService.GetAnalyzedRepositoriesAsync(repository => repository.UserId == 1);
removed

2019-05-17 09:27 UTC, ArBond commented on NugetAnalyzer.DAL/Interfaces/IVersionRepository.cs
> +        Task<IReadOnlyCollection<PackageVersion>> GetLatestPackageVersionsAsync(ICollection<int> packageIds);
done

2019-05-17 09:40 UTC, pryabov approved these changes
well done

2019-05-17 09:41 UTC, merged