Repository service.
AnyCase-Company-LTD/NugetAnalyzer pull request #38
Opened 2019-05-14 13:30 UTC by materiywakal

Repository mapper implemented.

2019-05-14 15:44 UTC, pryabov requested changes

2019-05-14 15:44 UTC, pryabov commented on NugetAnalyzer.BLL/Interfaces/IRepositoryMapper.cs
> +namespace NugetAnalyzer.BLL.Interfaces
@gennadybaranov what do you think. For me we need to get rid from this interface and class at all

2019-05-15 01:06 UTC, materiywakal commented on NugetAnalyzer.BLL/Interfaces/IRepositoryMapper.cs
> +namespace NugetAnalyzer.BLL.Interfaces
Maybe we don't need this interface at all and we don't need this class as dependency but we can use it as separate entity which we can initialize and use in methods. Also i can do this class disposable so we can include using construction.

2019-05-15 08:05 UTC, materiywakal commented on NugetAnalyzer.BLL/Interfaces/IRepositoryMapper.cs
> +namespace NugetAnalyzer.BLL.Interfaces
Bad thoughts coming in 4 a.m.

2019-05-15 09:25 UTC, pryabov commented on NugetAnalyzer.BLL/Interfaces/IRepositoryMapper.cs
> +namespace NugetAnalyzer.BLL.Interfaces
:) If you need to discuss something, pls contact with me directly

2019-05-15 10:36 UTC, pryabov requested changes

2019-05-15 10:36 UTC, pryabov commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +
Add code region to the file
`#region Private Methods`
And when in some other part of BLL will be needed the same functionality method can be extracted to some kind of helper

2019-05-15 10:36 UTC, pryabov commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +                var domainSolution = domainRepository.Solutions.FirstOrDefault(o => o.Name == solution.Name);
`o` - pl, use more sensible name

2019-05-15 10:36 UTC, pryabov commented on NugetAnalyzer.BLL/Services/RepositoryService.cs
> +            string packageName, string version, Project domainProject, Repository domainRepository)
in this case each argument from new line
```
private async Task<ProjectPackageVersion> CreatePackageAsync(
            string packageName, 
string version, 
Project domainProject, 
Repository domainRepository)
```

2019-05-16 10:39 UTC, pryabov approved these changes

2019-05-16 10:40 UTC, merged