Create error views (#39)
AnyCase-Company-LTD/NugetAnalyzer pull request #40
Opened 2019-05-16 13:04 UTC by pipalalala

Views for 404 and 500 error were made.

2019-05-16 13:04 UTC, materiywakal approved these changes

2019-05-16 13:17 UTC, AntsiferauGodel requested changes

2019-05-16 13:17 UTC, AntsiferauGodel commented on NugetAnalyzer.Web/Startup.cs
>              app.UseMvc();
remove UseMvc then

2019-05-16 14:38 UTC, pipalalala commented on NugetAnalyzer.Web/Startup.cs
>              app.UseMvc();
done

2019-05-16 14:46 UTC, AntsiferauGodel approved these changes
Seems ok

2019-05-16 14:57 UTC, maximKalinov approved these changes

2019-05-16 17:57 UTC, pryabov requested changes

2019-05-16 17:57 UTC, pryabov commented on NugetAnalyzer.Web/NugetAnalyzer.Web.csproj
> +    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.3" />
Why we need this reference?

2019-05-16 17:57 UTC, pryabov commented on NugetAnalyzer.Web/Startup.cs
> +                app.UseHsts();
Why we need `app.UseHsts()`?

2019-05-17 08:34 UTC, pipalalala commented on NugetAnalyzer.Web/NugetAnalyzer.Web.csproj
> +    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.3" />
it is used for compilation *.scss files

2019-05-17 08:43 UTC, pipalalala commented on NugetAnalyzer.Web/Startup.cs
> +                app.UseHsts();
Hsts is a security feature to force SSL. It was included because using of unprotected protocol can trigger a series of attacks.

2019-05-17 08:55 UTC, pryabov requested changes

2019-05-17 08:55 UTC, pryabov commented on NugetAnalyzer.Web/Startup.cs
> +                app.UseHsts();
No need for now.

2019-05-17 08:57 UTC, pipalalala commented on NugetAnalyzer.Web/Startup.cs
> +                app.UseHsts();
Ok, i'll remove this line.

2019-05-17 09:04 UTC, pipalalala commented on NugetAnalyzer.Web/Startup.cs
> +                app.UseHsts();
UPD: was removed

2019-05-17 10:03 UTC, AntsiferauGodel approved these changes
seems ok

2019-05-17 10:08 UTC, maximKalinov approved these changes

2019-05-17 11:29 UTC, pryabov approved these changes

2019-05-17 11:29 UTC, merged