Implement showing package information
AnyCase-Company-LTD/NugetAnalyzer pull request #48
Opened 2019-05-20 16:09 UTC by maximKalinov

Task #16

2019-05-21 09:00 UTC, ArBond requested changes

2019-05-21 09:00 UTC, ArBond commented on NugetAnalyzer.DAL/Interfaces/IProjectsRepository.cs
> +        Task<IReadOnlyCollection<Project>> GetCollectionIncludePackage(Expression<Func<Project, bool>> predicate);
Async

2019-05-21 09:00 UTC, ArBond commented on NugetAnalyzer.BLL/Interfaces/IProjectService.cs
> +        Task<ProjectReportDTO> GetProjectReport(int projectId);
Async

2019-05-21 09:05 UTC, maximKalinov commented on NugetAnalyzer.DAL/Interfaces/IProjectsRepository.cs
> +        Task<IReadOnlyCollection<Project>> GetCollectionIncludePackage(Expression<Func<Project, bool>> predicate);
done

2019-05-21 09:06 UTC, maximKalinov commented on NugetAnalyzer.BLL/Interfaces/IProjectService.cs
> +        Task<ProjectReportDTO> GetProjectReport(int projectId);
done

2019-05-21 09:06 UTC, ArBond approved these changes

2019-05-21 09:23 UTC, pryabov approved these changes
To be continued...

2019-05-21 09:23 UTC, pryabov commented on NugetAnalyzer.BLL.Test/Services/ProjectServiceTests.cs
> +            nUnitVersion = new PackageVersion
`nUnitPackageVersion`

2019-05-21 09:23 UTC, pryabov commented on NugetAnalyzer.BLL.Test/Services/ProjectServiceTests.cs
> +            moqVersion = new PackageVersion
`moqPackageVersion`
and below the same

2019-05-21 09:23 UTC, pryabov commented on NugetAnalyzer.BLL.Test/Services/ProjectServiceTests.cs
> +            packageLatestVersions = new List<PackageVersion>
`latestPackageVersions`

2019-05-21 09:23 UTC, pryabov commented on NugetAnalyzer.BLL/Services/ProjectService.cs
> +            IReadOnlyCollection<Project> projects = await ProjectRepository.GetCollectionIncludePackageAsync(proj => proj.Id == projectId);
Can be used `project` instead of `proj`

2019-05-21 09:23 UTC, pryabov commented on NugetAnalyzer.Dtos/Models/PackageReportDTO.cs
> +        public PackageVersionDTO Current { get; set; }
`CurrentPackageVersion`

2019-05-21 09:23 UTC, pryabov commented on NugetAnalyzer.Dtos/Models/PackageReportDTO.cs
> +        public PackageVersionDTO Latest { get; set; }
`LatestPackageVersion`

2019-05-21 09:23 UTC, pryabov commented on NugetAnalyzer.Dtos/Models/ProjectReportDTO.cs
> +    public class ProjectReportDTO : ProjectVersionReport
Why we created separate entities and named them `*ReportDTO ` can we reuse old ones like `*Report`
In this case `ProjectReportDTO` and `ProjectVersionReport`

2019-05-21 09:24 UTC, pryabov requested changes
Pls, check previously added comments

2019-05-21 13:10 UTC, maximKalinov commented on NugetAnalyzer.BLL/Services/ProjectService.cs
> +            IReadOnlyCollection<Project> projects = await ProjectRepository.GetCollectionIncludePackageAsync(proj => proj.Id == projectId);
I can't use project, because I already have a local variable 'project'

2019-05-22 08:30 UTC, maximKalinov commented on NugetAnalyzer.BLL.Test/Services/ProjectServiceTests.cs
> +            nUnitVersion = new PackageVersion
Done

2019-05-22 08:30 UTC, maximKalinov commented on NugetAnalyzer.BLL.Test/Services/ProjectServiceTests.cs
> +            moqVersion = new PackageVersion
done

2019-05-22 08:30 UTC, maximKalinov commented on NugetAnalyzer.BLL.Test/Services/ProjectServiceTests.cs
> +            packageLatestVersions = new List<PackageVersion>
done

2019-05-22 08:30 UTC, maximKalinov commented on NugetAnalyzer.Dtos/Models/PackageReportDTO.cs
> +        public PackageVersionDTO Current { get; set; }
done

2019-05-22 08:31 UTC, maximKalinov commented on NugetAnalyzer.Dtos/Models/PackageReportDTO.cs
> +        public PackageVersionDTO Latest { get; set; }
done

2019-05-22 08:55 UTC, pryabov requested changes

2019-05-22 08:55 UTC, pryabov commented on NugetAnalyzer.DAL/Interfaces/IProjectsRepository.cs
> +        Task<IReadOnlyCollection<Project>> GetCollectionIncludePackageAsync(Expression<Func<Project, bool>> predicate);
Do we need such method with Predicate?
For me if we needed to obtain only by Id this method can be done private and created a separate method like
`GetByIdWithIncludedPackageAsync`

2019-05-22 09:00 UTC, pryabov requested changes

2019-05-22 09:00 UTC, pryabov commented on NugetAnalyzer.Dtos/Models/Reports/ProjectReport.cs
> +
remove extra line

2019-05-22 11:23 UTC, pryabov approved these changes

2019-05-22 11:23 UTC, merged