Corrected a logging and exception handling
AnyCase-Company-LTD/NugetAnalyzer pull request #53
Opened 2019-05-23 14:34 UTC by ArBond

2019-05-23 15:30 UTC, maximKalinov approved these changes

2019-05-24 08:53 UTC, pryabov requested changes

2019-05-24 08:53 UTC, pryabov commented on NugetAnalyzer.Web/Middleware/ExceptionHandlingMiddleware.cs
> +            var body = request.Body;
`var` ty types everywhere

2019-05-24 09:04 UTC, ArBond commented on NugetAnalyzer.Web/Middleware/ExceptionHandlingMiddleware.cs
> +            var body = request.Body;
done

2019-05-24 09:15 UTC, pryabov approved these changes

2019-05-24 09:15 UTC, merged