Create repository report page
AnyCase-Company-LTD/NugetAnalyzer pull request #55
Opened 2019-05-24 09:26 UTC by maximKalinov

Task #50
Create Report partial view

2019-05-24 09:45 UTC, ArBond requested changes

2019-05-24 09:45 UTC, ArBond commented on NugetAnalyzer.Web/wwwroot/scripts/Shared/accordion.js
> +	let acc = document.getElementsByClassName("div__accordion");
Use one search style (as above, jquery)
and write please full name of the variable

2019-05-24 09:45 UTC, ArBond commented on NugetAnalyzer.Web/wwwroot/scripts/Shared/accordion.js
> +﻿(function Accordion() {
camelCase

2019-05-24 09:45 UTC, ArBond commented on NugetAnalyzer.Web/Controllers/RepositoryController.cs
> +        public async Task<IActionResult> Report()
please add [httpGet] attribute

2019-05-24 09:55 UTC, maximKalinov commented on NugetAnalyzer.Web/wwwroot/scripts/Shared/accordion.js
> +	let acc = document.getElementsByClassName("div__accordion");
done

2019-05-24 09:55 UTC, maximKalinov commented on NugetAnalyzer.Web/wwwroot/scripts/Shared/accordion.js
> +﻿(function Accordion() {
done

2019-05-24 09:55 UTC, maximKalinov commented on NugetAnalyzer.Web/Controllers/RepositoryController.cs
> +        public async Task<IActionResult> Report()
done

2019-05-24 11:37 UTC, ArBond approved these changes

2019-05-24 13:54 UTC, pryabov requested changes

2019-05-24 13:54 UTC, pryabov commented on NugetAnalyzer.Web/wwwroot/scripts/Account/profile.js
> +		}
format error

2019-05-24 13:54 UTC, pryabov commented on NugetAnalyzer.Web/Views/Account/Profile.cshtml
> +    <link href="~/stylesheets/Repository/Report.min.css" rel="stylesheet" />
Why `min`?

2019-05-27 08:33 UTC, maximKalinov commented on NugetAnalyzer.Web/wwwroot/scripts/Account/profile.js
> +		}
done

2019-05-27 08:35 UTC, maximKalinov commented on NugetAnalyzer.Web/Views/Account/Profile.cshtml
> +    <link href="~/stylesheets/Repository/Report.min.css" rel="stylesheet" />
Replaced everywhere by min

2019-08-02 07:13 UTC, pryabov approved these changes

2019-08-02 07:13 UTC, merged