T2
AnyCase-Company-LTD/NugetAnalyzer pull request #9
Opened 2019-04-22 07:03 UTC by maximKalinov

Create domain entities

2019-04-22 07:39 UTC, pipalalala requested changes

2019-04-22 07:39 UTC, pipalalala commented on NugetAnalyzer.DAL/Context/NugetAnalyzerDbContext.cs
> +            :base(options)
Please, add space before "base" keyword

2019-04-22 07:39 UTC, pipalalala commented on NugetAnalyzer.DAL/EntityConfigurations/ReferencePackageConfiguration.cs
> +            builder.HasKey(k => k.PackageId);
Please, change "k" to "p"

2019-04-22 07:39 UTC, pipalalala commented on NugetAnalyzer.DAL/EntityConfigurations/PackageConfiguration.cs
> +            builder.HasKey(k => k.PackageId);
Please, change "k" to "p" everywhere

2019-04-22 11:30 UTC, HenadziBaranau requested changes
BTW, could we remove `SetCompatibilityVersion` in Stratup? Also please allign Startup builder similar to entity type configurations

2019-04-22 11:30 UTC, HenadziBaranau commented on NugetAnalyzer.DAL/EntityConfigurations/ProjectConfiguration.cs
> +            builder.Property(p => p.Name).IsRequired().HasMaxLength(4096);
Please allign similar to code below. IMHO, it's easier to read:
```
builder
      .Property(p => p.Name)
      .IsRequired()
      .HasMaxLength(4096);
```

2019-04-22 11:30 UTC, HenadziBaranau commented on NugetAnalyzer.DAL/Context/NugetAnalyzerDbContext.cs
> +        public DbSet<User> Users { get; set; }
It's enough just to leave only `DbSet<User>`. All other collections are "reachable" from User base on navigation properties/foreign keys.

2019-04-22 11:30 UTC, HenadziBaranau commented on NugetAnalyzer.DAL/NugetAnalyzer.DAL.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.2.4" />
Why do we need this package?

2019-04-22 11:30 UTC, HenadziBaranau commented on NugetAnalyzer.Domain/Package.cs
> +        public ReferencePackage ReferencePackage { get; set; }
Could you please use empty line between properties decalration? The same one in interfaces. I really appreciate if you could follow suggested guideline.

2019-04-22 11:30 UTC, HenadziBaranau commented on NugetAnalyzer.Domain/Project.cs
> +        public int ProjectId { get; set; }
I prefer to use just `Id`. You are duplicating semantic prefix. Imagine code usage:
```
var project = new Project();
project.ProjectId = 1; 
// project.Id = 1; I would say it's more elegant.
```

2019-04-22 11:30 UTC, HenadziBaranau commented on NugetAnalyzer.Domain/PackageBase.cs
> +    public abstract class PackageBase
Try to avoid inheritance in EF Core. EF Core currently only supports [TPH ](https://www.learnentityframeworkcore.com/inheritance) strategy, that has 2 main disadavantages:
- Data integrity(I believe that you are aware about database normalization)
- Adds additional column to the table to differ types.

Think about using(not required, but probably make sense) - [Owned Types](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities).

2019-04-22 11:30 UTC, HenadziBaranau commented on NugetAnalyzer.DAL/EntityConfigurations/PackageConfiguration.cs
> +                .OnDelete(DeleteBehavior.SetNull);
Is it required? Why not Restrict or Cascade? Use cases when it's applicable?

2019-04-22 11:58 UTC, pipalalala approved these changes

2019-04-22 13:05 UTC, maximKalinov commented on NugetAnalyzer.DAL/EntityConfigurations/ProjectConfiguration.cs
> +            builder.Property(p => p.Name).IsRequired().HasMaxLength(4096);
Done

2019-04-22 13:05 UTC, maximKalinov commented on NugetAnalyzer.DAL/NugetAnalyzer.DAL.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.2.4" />
Remove it

2019-04-22 13:06 UTC, maximKalinov commented on NugetAnalyzer.Domain/Project.cs
> +        public int ProjectId { get; set; }
Done

2019-04-22 13:10 UTC, maximKalinov commented on NugetAnalyzer.DAL/EntityConfigurations/PackageConfiguration.cs
> +                .OnDelete(DeleteBehavior.SetNull);
Changed it on DeleteBehavior.Restrict

2019-04-22 13:11 UTC, gennadybaranov commented on NugetAnalyzer.DAL/EntityConfigurations/PackageConfiguration.cs
> +                .OnDelete(DeleteBehavior.SetNull);
@maximKalinov why DeleteBehavior.Restrict? :)

2019-04-22 16:14 UTC, maximKalinov commented on NugetAnalyzer.DAL/Context/NugetAnalyzerDbContext.cs
> +        public DbSet<User> Users { get; set; }
Done

2019-04-23 05:57 UTC, gennadybaranov requested changes

2019-04-23 05:57 UTC, gennadybaranov commented on NugetAnalyzer/appsettings.json
> +    "DefaultConnection": "Data Source=Test;Initial Catalog=Dev5;Integrated Security=True;"
It's better to use localhost for development purporses. Your approach forces all developers create SQL instance with name Test that is not suitable.
Also please find better name for database :)

2019-04-23 05:57 UTC, gennadybaranov commented on NugetAnalyzer/Startup.cs
> +            services.AddDbContext<NugetAnalyzerDbContext>(options =>
There is new feature - DbContext pooling. Please use [it](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.0#dbcontext-pooling).

2019-04-23 05:57 UTC, gennadybaranov commented on NugetAnalyzer.Domain/PackageBase.cs
> +    public abstract class PackageBase
That's fine. Agree with current approach. 

The only thing, please think about approach how are we going to use Version's components. 

- Do we leave them as they are and compare as regular numbers. 
- Do we want to move them to own type - Version?
- Do we create computed get property of .NET Version type?

2019-04-23 07:27 UTC, maximKalinov commented on NugetAnalyzer/appsettings.json
> +    "DefaultConnection": "Data Source=Test;Initial Catalog=Dev5;Integrated Security=True;"
Done

2019-04-23 07:28 UTC, maximKalinov commented on NugetAnalyzer/Startup.cs
> +            services.AddDbContext<NugetAnalyzerDbContext>(options =>
Done

2019-04-23 07:46 UTC, gennadybaranov approved these changes

2019-04-23 07:46 UTC, merged